modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Misaka2592/PowahExtension/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="Misaka2592"
    description='''Adds Mekanism-style tiered upgraders: sneak-right-click a Powah! machine to upgrade it to the next tier in place, keeping its energy, inventory and settings.'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="powah"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="architectury"
    mandatory=true
    versionRange="[9.0.0,)"
    ordering="AFTER"
    side="BOTH"
